### ISSUE TITLE
Not able to implement AreaShop API inside my plugin

### ISSUE THREAD

**Issue by o0sh4d0w0o** [md5sha256/AreaShop#27]
**Current behavior**
I want to add AreaShop as dependency to using the API using maven

I tried using jitpack but it failed

Here is my pom.xml implementation
```xml
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.md5sha256</groupId>
            <artifactId>AreaShop</artifactId>
            <version>2.7.15</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

Here is what's happened : 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project {projectName}: Compilation failure: Compilation failure:
[ERROR] {projectPath}/src/main/java/fr/{pluginDir}.java:[12,41] package me.wiefferink.areashop.events.ask does not exist
[ERROR] {projectPath}/src/main/java/fr/{pluginDir}.java:[13,44] package me.wiefferink.areashop.events.notify does not exist
[ERROR] {projectPath}/src/main/java/fr/{pluginDir}.java:[14,44] package me.wiefferink.areashop.events.notify does not exist
[ERROR] {projectPath}/src/main/java/fr/{pluginDir}.java:[15,44] package me.wiefferink.areashop.events.notify does not exist
[ERROR] {projectPath}/src/main/java/fr/{pluginDir}.java:[224,30] cannot find symbol
[ERROR]   symbol:   class SoldRegionEvent
[ERROR]   location: class {pluginNamespace}.{pluginName}.{PluginName}
[ERROR] {projectPath}/src/main/java/fr/{pluginDir}.java:[252,32] cannot find symbol
[ERROR]   symbol:   class ResoldRegionEvent
[ERROR]   location: class {pluginNamespace}.{pluginName}.{PluginName}
[ERROR] {projectPath}/src/main/java/fr/{pluginDir}.java:[280,29] cannot find symbol
[ERROR]   symbol:   class BuyingRegionEvent
[ERROR]   location: class {pluginNamespace}.{pluginName}.{PluginName}
[ERROR] {projectPath}/src/main/java/fr/{pluginDir}.java:[309,33] cannot find symbol
[ERROR]   symbol:   class DeletedRegionEvent
[ERROR]   location: class {pluginNamespace}.{pluginName}.{PluginName}
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I tried a second time by changing dependency by : 

```xml
        <dependency>
            <groupId>com.github.md5sha256.AreaShop</groupId>
            <artifactId>areashop</artifactId>
            <version>2.7.15</version>
            <scope>provided</scope>
        </dependency>
```

But got this : 

```
[ERROR] Failed to execute goal on project {projectName}: Could not resolve dependencies for project {pluginNamespace}:{pluginName}:jar:1.0.1: The following artifacts could not be resolved: com.github.md5sha256.AreaShop:areashop:jar:2.7.15 (absent), com.sk89q.worldedit:worldedit-core:jar:7.2.15 (absent), com.sk89q.worldedit:worldedit-bukkit:jar:7.2.15 (absent), com.sk89q.worldguard:worldguard-core:jar:7.0.9 (absent), com.sk89q.worldguard:worldguard-bukkit:jar:7.0.9 (absent), me.wiefferink:platform-interface:jar:2.7.15 (absent), me.wiefferink:paper:jar:2.7.15 (absent), me.wiefferink:bukkit-modern:jar:2.7.15 (absent): Could not find artifact com.github.md5sha256.AreaShop:areashop:jar:2.7.15 in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

I tried by building it myself and storing it in my mavenLocalRepo it works fine

My plugin will not being executed on my own machine so i need to import it from a public repository to make my plugin usable outside a local environment without having to build a local maven repo.

**Desired behavior**
I would like have a solution to using the AreaShop api through a public repo.

**Your environment**
* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: 1.20.2
* AreaShop version: 2.7.15

**Your config files**
x

**Comment by md5sha256** [comment]
Fixed. You should be able to access them in jitpack via commit hash or 2.7.16 when thats released.

**Comment by o0sh4d0w0o** [comment]
> Fixed. You should be able to access them in jitpack via commit hash or 2.7.16 when thats released.

Still have the issue.

It looks like there still no have com/github/md5sha256/AreaShop/areashop/{version}/areashop-{version}.jar

According jitpack build logs : 

```
✅ Build artifacts:
com.github.md5sha256.AreaShop:plugins:v2.7.16
com.github.md5sha256.AreaShop:fastasyncworldedit:v2.7.16
com.github.md5sha256.AreaShop:adapters:v2.7.16
com.github.md5sha256.AreaShop:areashop-interface:v2.7.16
com.github.md5sha256.AreaShop:areashop:v2.7.16
com.github.md5sha256.AreaShop:areashop-nms:v2.7.16
com.github.md5sha256.AreaShop:worldguard:v2.7.16
com.github.md5sha256.AreaShop:worldedit:v2.7.16

Files: 
com/github/md5sha256/AreaShop/plugins/v2.7.16
com/github/md5sha256/AreaShop/plugins/v2.7.16/plugins-v2.7.16.jar
com/github/md5sha256/AreaShop/plugins/v2.7.16/plugins-v2.7.16.module
com/github/md5sha256/AreaShop/plugins/v2.7.16/plugins-v2.7.16.pom
com/github/md5sha256/AreaShop/plugins/v2.7.16/plugins-v2.7.16.pom.md5
com/github/md5sha256/AreaShop/plugins/v2.7.16/plugins-v2.7.16.pom.sha1

com/github/md5sha256/AreaShop/fastasyncworldedit/v2.7.16
com/github/md5sha256/AreaShop/fastasyncworldedit/v2.7.16/fastasyncworldedit-v2.7.16.jar
com/github/md5sha256/AreaShop/fastasyncworldedit/v2.7.16/fastasyncworldedit-v2.7.16.module
com/github/md5sha256/AreaShop/fastasyncworldedit/v2.7.16/fastasyncworldedit-v2.7.16.pom
com/github/md5sha256/AreaShop/fastasyncworldedit/v2.7.16/fastasyncworldedit-v2.7.16.pom.md5
com/github/md5sha256/AreaShop/fastasyncworldedit/v2.7.16/fastasyncworldedit-v2.7.16.pom.sha1

com/github/md5sha256/AreaShop/adapters/v2.7.16
com/github/md5sha256/AreaShop/adapters/v2.7.16/adapters-v2.7.16.jar
com/github/md5sha256/AreaShop/adapters/v2.7.16/adapters-v2.7.16.module
com/github/md5sha256/AreaShop/adapters/v2.7.16/adapters-v2.7.16.pom
com/github/md5sha256/AreaShop/adapters/v2.7.16/adapters-v2.7.16.pom.md5
com/github/md5sha256/AreaShop/adapters/v2.7.16/adapters-v2.7.16.pom.sha1

com/github/md5sha256/AreaShop/areashop-interface/v2.7.16
com/github/md5sha256/AreaShop/areashop-interface/v2.7.16/areashop-interface-v2.7.16-sources.jar
com/github/md5sha256/AreaShop/areashop-interface/v2.7.16/areashop-interface-v2.7.16.jar
com/github/md5sha256/AreaShop/areashop-interface/v2.7.16/areashop-interface-v2.7.16.module
com/github/md5sha256/AreaShop/areashop-interface/v2.7.16/areashop-interface-v2.7.16.pom
com/github/md5sha256/AreaShop/areashop-interface/v2.7.16/areashop-interface-v2.7.16.pom.md5
com/github/md5sha256/AreaShop/areashop-interface/v2.7.16/areashop-interface-v2.7.16.pom.sha1

com/github/md5sha256/AreaShop/areashop/v2.7.16
com/github/md5sha256/AreaShop/areashop/v2.7.16/areashop-v2.7.16-original.jar
com/github/md5sha256/AreaShop/areashop/v2.7.16/areashop-v2.7.16-sources.jar
com/github/md5sha256/AreaShop/areashop/v2.7.16/areashop-v2.7.16.module
com/github/md5sha256/AreaShop/areashop/v2.7.16/areashop-v2.7.16.pom
com/github/md5sha256/AreaShop/areashop/v2.7.16/areashop-v2.7.16.pom.md5
com/github/md5sha256/AreaShop/areashop/v2.7.16/areashop-v2.7.16.pom.sha1

com/github/md5sha256/AreaShop/areashop-nms/v2.7.16
com/github/md5sha256/AreaShop/areashop-nms/v2.7.16/areashop-nms-v2.7.16-sources.jar
com/github/md5sha256/AreaShop/areashop-nms/v2.7.16/areashop-nms-v2.7.16.jar
com/github/md5sha256/AreaShop/areashop-nms/v2.7.16/areashop-nms-v2.7.16.module
com/github/md5sha256/AreaShop/areashop-nms/v2.7.16/areashop-nms-v2.7.16.pom
com/github/md5sha256/AreaShop/areashop-nms/v2.7.16/areashop-nms-v2.7.16.pom.md5
com/github/md5sha256/AreaShop/areashop-nms/v2.7.16/areashop-nms-v2.7.16.pom.sha1

com/github/md5sha256/AreaShop/worldguard/v2.7.16
com/github/md5sha256/AreaShop/worldguard/v2.7.16/worldguard-v2.7.16.jar
com/github/md5sha256/AreaShop/worldguard/v2.7.16/worldguard-v2.7.16.module
com/github/md5sha256/AreaShop/worldguard/v2.7.16/worldguard-v2.7.16.pom
com/github/md5sha256/AreaShop/worldguard/v2.7.16/worldguard-v2.7.16.pom.md5
com/github/md5sha256/AreaShop/worldguard/v2.7.16/worldguard-v2.7.16.pom.sha1

com/github/md5sha256/AreaShop/worldedit/v2.7.16
com/github/md5sha256/AreaShop/worldedit/v2.7.16/worldedit-v2.7.16.jar
com/github/md5sha256/AreaShop/worldedit/v2.7.16/worldedit-v2.7.16.module
com/github/md5sha256/AreaShop/worldedit/v2.7.16/worldedit-v2.7.16.pom
com/github/md5sha256/AreaShop/worldedit/v2.7.16/worldedit-v2.7.16.pom.md5
com/github/md5sha256/AreaShop/worldedit/v2.7.16/worldedit-v2.7.16.pom.sha1
```

There is only these two jar files, but not standalone areashop-v2.7.16.jar : 
```
com/github/md5sha256/AreaShop/areashop/v2.7.16/areashop-v2.7.16-original.jar
com/github/md5sha256/AreaShop/areashop/v2.7.16/areashop-v2.7.16-sources.jar
```

Is it normal or a mistake from my deps config ?

```
<dependency>
    <groupId>com.github.md5sha256.AreaShop</groupId>
    <artifactId>areashop</artifactId>
    <version>v2.7.16</version>
    <scope>provided</scope>
</dependency>
```

**Comment by md5sha256** [comment]
Ah, I see. "Yes" because the jar task produces a `AreaShop...-original.jar` to keep with the maven build convention back in the day. This should be fixed in e4b5398.

**Comment by md5sha256** [comment]
fixed in 4fd478dbc3

**Comment by md5sha256** [comment]
You'll need to use `4fd478dbc3` as your version tag but future release tags will also work

**Comment by o0sh4d0w0o** [comment]
Seems you fixed the AreaShop-{version}.jar (and main dependencies) successfully. But still have another issue.

I cannot include it as dependency using jitpack due dependencies issues, logs below : 
```
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.sk89q.worldedit:worldedit-core:jar:7.2.17 is missing, no dependency information available
[WARNING] The POM for com.sk89q.worldedit:worldedit-bukkit:jar:7.2.17 is missing, no dependency information available
[WARNING] The POM for com.sk89q.worldguard:worldguard-core:jar:7.0.9 is missing, no dependency information available
[WARNING] The POM for com.sk89q.worldguard:worldguard-bukkit:jar:7.0.9 is missing, no dependency information available
[WARNING] The POM for me.wiefferink:platform-interface:jar:2.7.17-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for me.wiefferink:paper:jar:2.7.17-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for me.wiefferink:bukkit-modern:jar:2.7.17-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.638 s
[INFO] Finished at: 2023-12-06T17:58:48+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project {projectName}: Could not resolve dependencies for project {pluginNamespace}:{pluginName}:jar:1.0.1: The following artifacts could not be resolved: com.sk89q.worldedit:worldedit-core:jar:7.2.17 (absent), com.sk89q.worldedit:worldedit-bukkit:jar:7.2.17 (absent), com.sk89q.worldguard:worldguard-core:jar:7.0.9 (absent), com.sk89q.worldguard:worldguard-bukkit:jar:7.0.9 (absent), me.wiefferink:platform-interface:jar:2.7.17-SNAPSHOT (absent), me.wiefferink:paper:jar:2.7.17-SNAPSHOT (absent), me.wiefferink:bukkit-modern:jar:2.7.17-SNAPSHOT (absent): com.sk89q.worldedit:worldedit-core:jar:7.2.17 was not found in https://repo.papermc.io/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of papermc has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

In my .m2 local maven repo it downloaded files like that with .lastUpdated instead a .jar (due missing POM from dependencies) : 
![image](https://github.com/md5sha256/AreaShop/assets/25451887/1e33141c-6a43-42ec-b46d-5f0de98c2f3a)

This happened for each jar section warns.

Tested with both :
```
<groupId>com.github.md5sha256</groupId>
<artifactId>AreaShop</artifactId>
```
and
```
<groupId>com.github.md5sha256.AreaShop</groupId>
<artifactId>areashop</artifactId>
```

I tried to clean my whole .m2 repo and recompiling again to make sure to have a clean base but, still same. I'm stuck again 🤣.

**Comment by md5sha256** [comment]
do not use 2.7.17 as that has not been released onto jitpack (nor does it exist). Use a specific commit hash as your version, for example: 
`<version>4fd478dbc3</version>`
until the next release (which may be 2.7.17) sometime in the future

**Comment by o0sh4d0w0o** [comment]
> do not use 2.7.17 as that has not been released onto jitpack (nor does it exist). Use a specific commit hash as your version, for example: `<version>4fd478dbc3</version>` until the next release (which may be 2.7.17) sometime in the future

That's the one i used :
![image](https://github.com/md5sha256/AreaShop/assets/25451887/89fc5334-e34a-4ddc-90f4-0458fc2108c9)

**Comment by md5sha256** [comment]
use `areashop` (lowecase) in the artifactId

**Comment by o0sh4d0w0o** [comment]
Done : 
![image](https://github.com/md5sha256/AreaShop/assets/25451887/44820a63-9677-435e-ba15-524f146dec03)

But still :
```
The following artifacts could not be resolved: me.wiefferink:platform-interface:jar:2.7.17-SNAPSHOT (absent), me.wiefferink:paper:jar:2.7.17-SNAPSHOT (absent), me.wiefferink:bukkit-modern:jar:2.7.17-SNAPSHOT (absent): Could not find artifact me.wiefferink:platform-interface:jar:2.7.17-SNAPSHOT in sonatype (https://oss.sonatype.org/content/groups/public/) -> 
```

**Comment by md5sha256** [comment]
have you tried to with -U to force dependencies to resolve?

**Comment by o0sh4d0w0o** [comment]
> have you tried to with -U to force dependencies to resolve?

Yeah i use this : 
![image](https://github.com/md5sha256/AreaShop/assets/25451887/92daefda-49e9-46c6-9341-1ec7b78fff59)

**Comment by md5sha256** [comment]
I think your best bet at the moment is to exclude those artifacts. I'll fix this by just not publishing these artifacts

https://jitpack.io/com/github/md5sha256/AreaShop/areashop/4fd478dbc3/areashop-4fd478dbc3.pom
Specifically the empty `:paper` and `:platform-interface` projects are included but their versions are not changed to the commit hash. This was because the project excluded publishing tasks for these submodules... but they are still required for deployment of a non-api artifact

**Comment by o0sh4d0w0o** [comment]
> `4fd478dbc3`

I did that currently, and i'll remove when you'll do the fix : 
![image](https://github.com/md5sha256/AreaShop/assets/25451887/392e3acb-2340-4782-977a-5d27438f6673)

Looks like the build was successful now, i'll try my plugin to be sure nothing was broke.

**Comment by md5sha256** [comment]
fully fixed in 3348e5b697, you won't need to exclude those artifacts now

**Comment by o0sh4d0w0o** [comment]
Works fine. Issue solved, thanks.
